---
title: "Planificación Semanal MAT3 2019-2020"
author: "Ricardo"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    keep_md: yes
    number_sections: yes
    toc: yes
  pdf_document: default
  word_document: default
---


# Enlaces 

  + [Enlaces al  github de planificación](https://ricuib.github.io/mat3)
  + [Enlaces al material](https://ricuib.github.io/Enlaces/)


## PLANIFICACIÓN SEMANAL  A DISTANCIA

Iré informando sobre la marcha en  Aula digital de la UIB o en otros foros que acordemos.

### ENTREGAS Y CONTROLES PENDIENTES

* CONTROL FINAL día 12 de junio  a las 17:00 (duración aproximada 3 horas) por Aula Digital.
* CONTROL FINAL RECUPERACIÓN día 10 de julio  a las 9:00 (duración aproximada 3 horas ) por Aula Digital.
* (PROVISONAL) ENTREGA proyecto FINAL  o bien el día día 12 de junio  y  o el día  10 de julio.

* (PROVISONAL) Entrega de problemas 3 día 31 de mayo.
* (PROVISONAL) Entrega de problemas 4 (y última) día 11 de junio.


### **Semana 15 del  1 de junio  al  7 de junio**

**Provisional: Regresión lineal simple y múltiple (la múltiple es opcional)**


* Lecciones de la **Sección 11 de curso de estadística Inferencial** [Clase 148: El problema de la regresión lineal simple ](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17482878#overview)  hasta la clase 
[Clase 187: Contraste de hipótesis para los parámetros Beta_i ](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17493358#overview)
* Temas del libro [Tema 8 Regresión lineal: desde el principio hasta la sección 8.2.9](
https://joanby.github.io/bookdown-estadistica-inferencial/regresi%C3%B3n-lineal.html)

* Presentaciones [Tema 8 Regresión lineal: desde el pricipio hasta la TRANSPARENCIA 143](https://joanby.github.io/estadistica-inferencial/Tema-8---RegresionLineal#1)


* Opcional Tema 9  de clustering...


### **Semana 14 del  25 de mayo  al  31  de mayo**

**Provisional: Acabar problemas tema 7 ANOVA de una vía y comenzar tema 8 Regresión**


* Clases: Grupo Grande COLLABORATE Y DISCORD:  Quedaremos en clase y para fijar los contenidos y hacer problemas. 
  + GG1: martes 9:30 y jueves 12:30 (están invitados los del grupo 3)
  + GG3 miércoles a las 9:30 y jueves a las 9:30 (están invitados los del grupo 1)


* Trabajo  de la semana:
 

  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008).
**Sección 11: Regresión Lineal** [Sección 1: desde la clase 175: El problema de la regresión lineal simple](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17422338#overview) hasta   la clase [195: EL resumen de toda la regresión lineal](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17494662#overview).
  + [Tema 8 del libro; Regresión linealsimple secciones 8.1 y   la 8.3](https://joanby.github.io/bookdown-estadistica-inferencial/regresi%C3%B3n-lineal.html#regresi%C3%B3n-lineal-simple)[Tema 7 del libro :ANOVA SOLO introducción y secciones 7.1, 7.2 y 7.3](https://joanby.github.io/bookdown-estadistica-inferencial/an%C3%A1lisis-de-la-varianza.html#anova-de-un-factor)
  + Acabar (comprobación hipçotesis ANOVA) [Tema 7 Análisis de la Varianza:  solo hasta LA TRANS 114](https://joanby.github.io/estadistica-inferencial/Tema-7---ANOVA#1)






* Nuevos problemas propuestos y resueltos  el Tema 8:
  + [Tema 8 Regressión lineal, enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/Tema8_Regresion_Lineal_taller1.pdf), y las soluciones [Tema 6 Contrastes de independencia y homogeneidad. Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema8_Regresion_SOLUCIONES.pdf). Los Rmd [enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/Tema8_Regresion_Lineal_taller1.Rmd) y [soluciones(https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema8_Regresion_SOLUCIONES.Rmd)]
 
  









### **Semana 13 del  18 de mayo  al 24 de mayo**

**Independencia y Homogeneidad. ANOVA 1 VIA y  análisis post-hoc**


* Clases: Grupo Grande COLLABORATE Y DISCORD:  Quedaremos en clase y para fijar los contenidos y hacer problemas. 
  + GG1: martes 9:30 y jueves 12:30 (están invitados los del grupo 3)
  + GG3 miércoles a las 9:30 y jueves a las 9:30 (están invitados los del grupo 1)


* Trabajo  de la semana:
 
  + En paralelo a las lecciones del curso que se se piden (y solo esa parte) y como soporte de R id consultando las Lecciones de [AprendeR2](https://cescrossello.github.io/AprendeR-II/index.html):[Contrastes de independencia y homogeneidad](https://cescrossello.github.io/AprendeR-II/chap-indep.html),[Introducción  a la Estadística Multimensional](https://cescrossello.github.io/AprendeR-II/introduccion-a-la-estadistica-descriptiva-multidimensional.html).

  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008).
**Sección 9: Contrastes de Independencia y Homogeneidad: las clases (incluye  ejemplos)** [Sección 9: desde la clase 137: Ejemplo ¿Reducen las vacunas el riesgo de enfermar?](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17422338#overview) hasta   la clase [146: La importancia del diseño experimental](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17422798#overview). **Sección 10 ANOVA** de la lección [148: Análisis de la varianza entre Subpoblaciones](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17427636#overview)  a la lección [154; Comparación por pareja, test de Duncan y de Tukey](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17430098#overview)
  + [Tema 6 del libro :Contrastes de independencia y homogeneidad](https://joanby.github.io/bookdown-estadistica-inferencial/contrastes-de-independencia-y-homogeneidad.html), y  también  [Tema 7 del libro :ANOVA SOLO introducción y secciones 7.1 y 7.2](https://joanby.github.io/bookdown-estadistica-inferencial/an%C3%A1lisis-de-la-varianza.html#anova-de-un-factor)
  + [Tema 6 presentaciones Contrastes de independencia y homogeneidad: transparencias 1 a la 98](https://joanby.github.io/estadistica-inferencial/Tema-6---IndepHomog#1), y  también [Tema 7 Análisis de la Varianza:  solo hasta LA TRANS 100](https://joanby.github.io/estadistica-inferencial/Tema-7---ANOVA#1)



* Nuevos problemas propuestos y resueltos  el Tema 5 y ALGUNOS del tema 6:
  + [Tema 6 Contrastes de independencia y homogeneidad. Enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/Tema6_Independencia_y_Homogeneidad_taller1.pdf), y las soluciones [Tema 6 Contrastes de independencia y homogeneidad. Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema6_Independencia_SOLUCIONES.pdf)
  + [Tema 7 ANOVA  sólo secciones 7.1 y 7.2. Enunciados 1 y 2](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/Tema7_Analisis_Varianza_taller1.pdf), y las soluciones [Tema 7 ANOVA  sólo secciones 7.1 y 7.2. Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema7_ANOVA_SOLUCIONES.pdf)
  
  
  
  

### **Semana 12 del  11 de mayo  al 17 de mayo**


**Bondad de ajuste: test NO paramétricos**


* Clases: Grupo Grande COLLABORATE Y DISCORD:  Quedaremos para clase y para fijar las tareas para FINALIZAR ESTE CURSO. 
  + GG1: martes 9:30 y jueves 12:30 (están invitados los del grupo 3)
  + GG3 miércoles a las 9:30 y jueves a las 9:30 (están invitados los del grupo 1)


* Trabajo  de la semana:
 
  + En paralelo a las lecciones del curso que se se piden (y solo esa parte) y como soporte de R id consultando las Lecciones de [AprendeR2](https://aprender-uib.github.io/AprendeR2/index.html):[Contrastes de bondad de ajuste](https://aprender-uib.github.io/AprendeR2/chap-contrastes.html),[Contrastes de independencia y homogeneidad ajuste](https://cescrossello.github.io/AprendeR-II/chap-indep.html),[Introducción  a la Estadística Multimensional](https://cescrossello.github.io/AprendeR-II/introduccion-a-la-estadistica-descriptiva-multidimensional.html).


  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008)
Sección 8  Contrastes de hipótesis NO paramétricos: las clases (incluye  ejemplos)[116: Contrastes Paramétricos versus no Paramétricos](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17372742#overview)  a la
clase [132: Test omnibus de Agostino-Pearson](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17374692#overview).
  + [Tema 5 del libro :Bondad de Ajuste](https://joanby.github.io/bookdown-estadistica-inferencial/bondad-de-ajuste.html)
  + [Tema 5 presentaciones: transparencias 1 a la 98](https://joanby.github.io/estadistica-inferencial/Tema-5---BondadAjuste#1)

  


* Nuevos problemas propuestos y resueltos  el Tema 4 y del tema 5:
  + [Tema 4 Contraste Hipótesis Taller1: Enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema4_Contraste_hip%C3%B3tesis_taller1.pdf),[Tema 4 Contraste Hipótesis Taller1: Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema4_Contraste_hipótesis_taller1_SOLUCIONES.pdf)
  + [Tema 4 Contraste Hipótesis Taller2: Enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema4_Contraste_hip%C3%B3tesis_taller2.pdf),[Tema 4 Contraste Hipótesis Taller2: Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema4_Contraste_hipótesis_taller2_SOLUCIONES.pdf)
  + [Tema 4 Contraste Hipótesis Taller3: Enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema4_Contraste_hip%C3%B3tesis_taller3.pdf),[Tema 4 Contraste Hipótesis Taller3: Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema4_Contraste_hipótesis_taller3_SOLUCIONES.pdf)
  + [Tema 5 Bondad de Ajuste Taller1: Enunciados](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/Tema5_Bondad_de_Ajuste_taller1.pdf),[Tema 5 Bondad de Ajuste Taller1: Soluciones](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema5_Bondad_Ajuste_SOLUCIONES.pdf)





### **Semana 11 del  4 de mayo  al 10 de mayo**


* Clases: Grupo Grande COLLABORATE Y DISCORD:  Tutorías y talleres en linea.   
  + GG1: martes 9:30 y jueves 12:30 (están invitados los del grupo 3)
  + GG3 miércoles a las 9:30 y jueves a las 9:30 (están invitados los del grupo 1)


* Trabajo  de la semana:
 
  + Lecciones de [AprendeR2](https://aprender-uib.github.io/AprendeR2/index.html):[Acabar la lección lección 5: Contrastes de hipótesis](https://aprender-uib.github.io/AprendeR2/chap-contrastes.html).


  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008)
Sección 7  Contrastes de hipótesis paramétricos: las lecciones [89: Contraste de hipótesis de dos muestras](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16621992#overview)  a la
[107  inclusive. Contraste para proporciones binom.test](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17201856#overview).
  + [Tema 4 del libro :Contrastes hipótesis paramétricos secciones 4.7 a 4.12 inclusive ](https://joanby.github.io/bookdown-estadistica-inferencial/contrastes-de-hip%C3%B3tesis-param%C3%A9tricos.html)
  + [Tema 4 presentaciones: transparencias 141 a la 258](https://joanby.github.io/estadistica-inferencial/Tema-4---ContrasteHipotesis#1)

  


* Estad atentos a  nuevos problemas de contrastes. Acabad los problemas de Estimación puntual que [están resueltos Las soluciones están en esta dirección](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones)

 
* Esta semana saldrá el enunciado de otra entrega en grupo. Lo comentaremos en la clase del jueves


  


* **Tenéis que ACABAR**  los problemas de ESTIMACIÓN POR INTERVALOS TEMA 3 son dos talleres **PREGUNTAS TIPO EXAMEN FINAL**:
  + [Enunciados tema 3: Estimación por intervalos - taller 1](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema3_intervalos_de_confianza_taller1.pdf), [soluciones tema 3 taller 1](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema3_intervalos_de_confianza_taller1_SOLUCIONES.pdf).
  + [Enunciados tema 3: Estimación por intervalos- taller 2](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema3_intervalos_de_confianza_taller2.pdf), [soluciones tema 3 taller 2](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/soluciones/tema3_intervalos_de_confianza_taller2_SOLUCIONES.pdf).




### **Semana 10 del 27 de abril al 3 de mayo**

* Grupo Grande COLLABORATE Y DISCORD:  Tutorías y talleres en linea.   
  + GG1: martes 9:30 y jueves 12:30 (están invitados los del grupo 3)
  + GG3 miércoles a las 9:30 y jueves a las 9:30 (están invitados los del grupo 1)

Lecciones de [AprendeR2](https://aprender-uib.github.io/AprendeR2/):[Id leyendo la lección 5: Contrastes de hipótesis](https://aprender-uib.github.io/AprendeR2/contrastos-dhip%C3%B2tesis-dun-i-dos-par%C3%A0metres.html).

 


  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008)
Sección 7  Contrastes de hipótesis paramétricos: las lecciones [73](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16621992#overview)  a la
[88 inclusive](https://www.udemy.com/course/estadisticainferencial/learn/lecture/17201856#overview).
  + [Tema 4 del libro :Contrastes hipótesis paramétricos secciones 4.1 a 4.7 inclusive ](https://joanby.github.io/bookdown-estadistica-inferencial)
  + [Tema 4 presentaciones: transparencias 1 a 140](https://joanby.github.io/estadistica-inferencial/Tema-4---ContrasteHipotesis#1)

  


* De momento **NO** hay más problemas propuestos. **Tenéis que ACABAR**  los problemas de Estimación puntual que [están resueltos Las soluciones están en esta dirección](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones)
 
* **HAY QUE ENTREGAR la FASE 2 del  PROYECTO**: pedid tutoría hasta el jueves en horas de clase presencial. 








### **Semana 9 del 20 de abril al  26 de abril**

* Grupo Grande BBCOLLABORATE Y DISCORD 
  + GG1: martes  9:30 y jueves 12:30 (están invitados los del grupo 3)
  + GG3 miércoles a las 9:30 y jueves a las 9:30 (están invitados los del grupo 1)

**ATENCION SALDRÁN EN EL EXAMEN FINAL: EMPEZAD** Lecciones de [AprendeR2](https://aprender-uib.github.io/AprendeR2/):

  + [1. Distribuciones de  probabilidad](https://cescrossello.github.io/AprendeR-II/AprendeR2/chap-distr.html)
  + [2. Conceptos básicos de muestreo](https://cescrossello.github.io/AprendeR-II/chap-muestreo.html)
  + [3. Estimación puntual](https://cescrossello.github.io/AprendeR-II/chap-estimacion.html)
  + [4. Intervalos de confianza](https://cescrossello.github.io/AprendeR-II/chap-IC.html)

Los recurso del material de los cursos de estadística inferencial 

* [Curso completo de estadística inferencial con R y Python bookdown. EN CONSTRUCCIÓN](https://joanby.github.io/bookdown-estadistica-inferencial)
* [Presentaciones](https://joanby.github.io/estadistica-inferencial)
* [Presentaciones repositorio](https://github.com/joanby/estadistica-inferencial)
   




  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008)
Sección 5  intervalos de confianza: las lecciones [49](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16621992#overview)  A  [66](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16621992#overview).
  +  Y los correspondientes temas:   [3. Intervalos de confianza](https://joanby.github.io/estadistica-inferencial/Tema-3---IC#1)
  


* Problemas propuestos tenéis que ir ACABANDO los problemas de Estimación puntual que [están resueltos Las soluciones están en esta dirección](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones)
 
  + Estimación 1  :[pdf](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller1.pdf), [Rmd](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller1.Rmd). [Soluciones](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones).
  + Estimación 2  :[pdf](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller2.pdf), [Rmd](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller2.Rmd). [Soluciones](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones).
  + Estimación 3  :[pdf](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller3.pdf), [Rmd](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller3.Rmd).[Soluciones](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones).



*  PROYECTO FASE 2 : Estad atentos a  Aula Digital iré dando indicaciones y fechas para la fase dos del proyecto. Esta 
SEMANA TUTORIA POR GRUPO.  En la tutoría os evalúo el proyecto  FASE 1 en directo y  os doy INDICACIONES  para la fase 2



### **Semana 8 del 6 de abril al  12 de abril Y PASCUA** 

* Grupo Grande BBCOLLABORATE Y DISCORD (GG1 martes  9:00 y  GG3 miércoles a las 9:00): 


Los recurso del material de los cursos de estadística inferencial 

* [Curso completo de estadística inferencial con R y Python bookdown. EN CONSTRUCCIÓN](https://joanby.github.io/bookdown-estadistica-inferencial)
* [Presentaciones](https://joanby.github.io/estadistica-inferencial)
* [Presentaciones repositorio](https://github.com/joanby/estadistica-inferencial)
   




  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16492008)
A acabar la sección 4 (estimación puntual) (lecciones [33](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16505056#overview)  a la  [48](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16618414#overview) inclusive; los temas de python son opcionales). 
En pascua podéis pegar un vistazo  a los vídeos de la sección 5  de intervalos de confianza las lecciones [49](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16621992#overview)  a [66](https://www.udemy.com/course/estadisticainferencial/learn/lecture/16621992#overview).
  +  Y los correspondientes temas:  [Muestreo Estadístico](https://joanby.github.io/estadistica-inferencial/Tema-1---Muestreo#1), [2.Estimación Puntual](https://joanby.github.io/estadistica-inferencial/Tema-2---Estimaci%C3%B3n#1)  y pegad un vistazo al tema  [3. Intervalos de confianza](https://joanby.github.io/estadistica-inferencial/Tema-3---IC#1)
  


* Problemas propuestos tenéis que ir haciendo los problemas de Estimación puntual que [están resueltos Las soluciones están en esta dirección](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones)
 
  + Estimación 1  :[pdf](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller1.pdf), [Rmd](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller1.Rmd). [Soluciones](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones).
  + Estimación 2  :[pdf](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller2.pdf), [Rmd](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller2.Rmd). [Soluciones](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones).
  + Estimación 3  :[pdf](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller3.pdf), [Rmd](https://github.com/joanby/estadistica-inferencial/blob/master/ejercicios/talleres%20propuestos/enunciados/tema2_estimacion_ejercicios_taller3.Rmd).[Soluciones](https://github.com/joanby/estadistica-inferencial/tree/master/ejercicios/talleres%20propuestos/soluciones).



*  PROYECTO FASE 2 : Estad atentos a  Aula Digital iré dando indicaciones y fechas para la fase dos del proyecto. Tendríais que enseñarme algo de la fase 2 sobre el  24 de abril y entregarla sobre el  3 de mayo. Haré tutorías por grupos.





### **Semana 7 del 30 de marzo al 5 de abril** 

* Grupo Grande BBCOLLABORATE Y DISCORD (GG1 martes  9:00 + 1 taller el jueves a las 12:30 a 13:30, GG3 miércoles y jueves (taller)  a las 9:00): 


Los recursos del material del curso de estadística inferencial 

* [Curso completo de estadística inferencial con R y Python bookdown. EN CONSTRUCCIÓN](https://joanby.github.io/bookdown-estadistica-inferencial)
* [Presentaciones](https://joanby.github.io/estadistica-inferencial)
* [Presentaciones repositorio](https://github.com/joanby/estadistica-inferencial)
   


* Estudiad: EMPEZAMOS ESTADÍSTICA INFERENCIAL: 


  + [Enlace a  los vídeos en Udemy](https://www.udemy.com/course/estadisticainferencial/learn/practice/1156538?couponCode=558B1259A85F3C62C9F9#overview)
     secciones 3 (todas las lecciones) y sección 4 (lecciones 23 a 32 inclusive). 
 
  +  Y los correspondientes temas:  [Muestreo Estadístico](https://joanby.github.io/estadistica-inferencial/Tema-1---Muestreo#1), [2.Estimación Puntual](https://joanby.github.io/estadistica-inferencial/Tema-2---Estimaci%C3%B3n#1)
  


* Problemas propuestos CONTINUAD con los problemas de 
  + Introducción variables aleatorias:
  [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-2---Variables-Aleatorias.pdf),[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%202%20-%20Variables%20Aleatorias.Rmd). 
  + Distribuciones notables discretas: [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_discretas.pdf),[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_discretas.Rmd).
  + Distribuciones notables continuas:[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_continuas.pdf), [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_continuas.Rmd).

*  Problemas  para entregar: Estad atentos a  Aula Digital saldrán algunos ejercicios para entregar.






### **Semana 6 del 23 de marzo al 30 de marzo** 

* Grupo Grande (3 horas martes GG1 8:30 a 11:30 + 1 taller el jueves a las 12:30 a 13:30, GG3 2 horas martes 8:30 a 10:30 y una hora jueves 8:30  a 9:30 y una hora taller jueves a las 9:30 a 10:30  ): 


Introducción a variables variables: Sólo estudiaremos el  **TEOREMA CENTRAL DEL LÍMITE**

Leer el las siguientes  secciones del [Curso de Probabilidad y variables aleatorias para ML con R y Python](https://joanby.github.io/bookdown-probabilidad/).
 
 [Tema 7  Ley de los grandes números y Teorema Central del Límite](https://joanby.github.io/bookdown-probabilidad/ley-de-los-grandes-n%C3%BAmeros-y-teorema-central-del-l%C3%ADmite.html#muestras-aleatorias-simples):
 
 
 
 
  * [Sección 7.1 Muestras aleatorias simples](https://joanby.github.io/bookdown-probabilidad/ley-de-los-grandes-n%C3%BAmeros-y-teorema-central-del-l%C3%ADmite.html#muestras-aleatorias-simples)
  * [Sección 7.2 Convergencia se sucesiones de variables aleatorias SOLO LA INTRODUCCIóN](https://joanby.github.io/bookdown-probabilidad/ley-de-los-grandes-n%C3%BAmeros-y-teorema-central-del-l%C3%ADmite.html#convergencia-de-sucesiones-de-variables-aleatorias) y la [Subsección 7.2.3 Convergencia en ley o en distribución]()
  * [Sección 7.3 ENTERA: Teorema Central del Límite](https://joanby.github.io/bookdown-probabilidad/ley-de-los-grandes-n%C3%BAmeros-y-teorema-central-del-l%C3%ADmite.html#teorema-central-del-l%C3%ADmite)

* Ejercicios SOLO LA SECCIÓN el TEOREMA CENTRAL DEL LíMITE:[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-7---TCL.pdf),[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-7---TCL.Rmd).


* Problemas propuestos
  + Introducción variables aleatorias:
  [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-2---Variables-Aleatorias.pdf),[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%202%20-%20Variables%20Aleatorias.Rmd). 

* Acabar los problemas de :
  + Distribuciones notables discretas: [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_discretas.pdf),[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_discretas.Rmd).
  + Distribuciones notables continuas:[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_continuas.pdf), [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_continuas.Rmd).

*  Problemas  para entregar: Estad atentos a  Aula Digital saldrá algunos ejercicios para entregar la semana que viene.









### **Semana 5 del 16 de marzo al 22 de marzo** 

* Grupo Grande (3 horas martes GG1 8:30 a 11:30 + 1 taller el jueves a las 12:30 a 13:30, GG3 2 horas martes 8:30 a 10:30 y una hora jueves 8:30  a 9:30 y una hora taller jueves a las 9:30 a 10:30  ): 
Acabaremos  los temas de  distribuciones notables **MIRANDO LOS VIDEOS**: 
  + [Distribuciones Notables Parte I: Distribuciones Discretas](https://joanby.github.io/probabilidad/Tema_3_1_Notables#1). VIDEOS [Sección 8 curso de UDEMY](https://www.udemy.com/course/probabilidad-y-variables-aleatorias-para-ml-con-r-y-python/)
  + [Distribuciones Notables Parte II: Distribuciones Continuas. Cuantiles](https://joanby.github.io/probabilidad/Tema_3_2_Notables#1). VIDEOS [Sección 9 curso de UDEMY](https://www.udemy.com/course/probabilidad-y-variables-aleatorias-para-ml-con-r-y-python/)

* Problemas propuestos
  + Introducción variables aleatorias: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%202%20-%20Variables%20Aleatorias.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-2---Variables-Aleatorias.pdf)
  + Distribuciones notables discretas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_discretas.Rmd), [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_discretas.pdf)
  + Distribuciones notables continuas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_continuas.Rmd)
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_continuas.pdf)

*  Taller  evaluable: Estad atentos a  Aula Digital


## PLANIFICACIÓN SEMANAL PRESENCIAL



### **Semana 4 del 9 de marzo al 15 de marzo** 

* Grupo mediano:  Hay taller EVALUABLE GR1 de 12:30 a 14:30. GR3 de 8:30 a 10:30 en l aula habitual.

* Trabajo en casa: Repasar los ejercicios de AprendeR1 y  los talleres de R


**Semana 4 del 9 de marzo al 15 de marzo** 


  + [Enlaces al  github de planificación](https://www.github.com/ricuib/mat3)
  + [Enlaces al material](https://ricuib.github.io/Enlaces/).


* Grupo Grande (3 horas martes GG1 y 2 horas miércoles y  2 horas jueves GR3: 
Acabaremos  los temas de  distribuciones notables: 
  + [Distribuciones Notables Parte I: Distribuciones Discretas](https://joanby.github.io/probabilidad/Tema_3_1_Notables#1)
  + [Distribuciones Notables Parte II: Distribuciones Continuas. Cuantiles](https://joanby.github.io/probabilidad/Tema_3_2_Notables#1)

* Problemas propuestos
  + Introducción variables aleatorias: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%202%20-%20Variables%20Aleatorias.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-2---Variables-Aleatorias.pdf)
  + Distribuciones notables discretas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_discretas.Rmd), [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_discretas.pdf)
  + Distribuciones notables continuas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_continuas.Rmd)
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_continuas.pdf)

* Grupo mediano:  No hay  taller el GR1 no viene y el GR3  tenéis teoría

* Trabajo en casa: Estudiar los siguientes temas de AprendeR1 y hacer los cuestionarios y problemas propuestos:
  + [Descripción de datos cuantitativos](https://aprender-uib.github.io/AprendeR1/chap-quan.html)
  + [Datos cuantitativos agrupados](https://aprender-uib.github.io/AprendeR1/datos-cuantitativos-agrupados.html)
  + [Gráficos avanzados](https://aprender-uib.github.io/AprendeR1/graficos-avanzados.html)


### **Semana 3 del 2 de marzo al 8 de marzo** 

* Grupo Grande: 
Acabaremos el  tema 
[Introducción variables aleatorias](https://joanby.github.io/bookdown-probabilidad/variables-aleatorias.html). 
Comenzaremos el tema de distribuciones notables que está dividido en dos partes:
  + [Distribuciones Notables Parte I: Distribuciones Discretas](https://joanby.github.io/probabilidad/Tema_3_1_Notables#1)
  + [Distribuciones Notables Parte II: Distribuciones Continuas. Cuantiles](https://joanby.github.io/probabilidad/Tema_3_2_Notables#1)

* Problemas propuestos
  + Introducción variables aleatorias: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%202%20-%20Variables%20Aleatorias.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-2---Variables-Aleatorias.pdf)
  + Distribuciones notables discretas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_discretas.Rmd), [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_discretas.pdf)
  + Distribuciones notables continuas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_continuas.Rmd)
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_continuas.pdf)

* Grupo mediano:  Dos horas de taller el jueves, traed los portátiles. Haremos problemas de combinatoria y probabilidad, también haremos ejercicios de los temas de R.
* Trabajo en casa: Estudiar los siguientes temas de AprendeR1 y hacer los cuestionarios y problemas propuestos:
  + [Gráficos básicos](https://aprender-uib.github.io/AprendeR1/chap-plot.html)
  + [Descripción de datos cualitativos](https://aprender-uib.github.io/AprendeR1/chap-edqual.html)
  + [Descripción  de datos ordinales](https://aprender-uib.github.io/AprendeR1/chap-ord.html). 
  
  ¡¡¡ Son opcionales!!!! Los temas [Estructuras de control basicas](https://aprender-uib.github.io/AprendeR1/chap-for.html)  y [Distribuciones de probabilidad](https://aprender-uib.github.io/AprendeR1/chap-distr.html) los veremos en clase de grupo grande y de mediano. 



### **Semana 2 del 24 de febrero al al  1 de marzo** [Enlaces al material](https://ricuib.github.io/Enlaces/).

* Grupo Grande: Probabilidad: [Prerrequisitos](https://joanby.github.io/bookdown-probabilidad/pre-requisitos-teor%C3%ADa-de-conjuntos-y-combinatoria.html), [Probabilidad](https://joanby.github.io/bookdown-probabilidad/probabilidad.html). [Introducción variables aleatorias](https://joanby.github.io/bookdown-probabilidad/variables-aleatorias.html). 
* Problemas propuestos
  + Prerrequisitos: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%200%20-%20Combinatoria.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-0---Combinatoria.pdf)
  + Probabilidad: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%201%20-%20Probabilidad.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-1---Probabilidad.pdf)
* Grupo mediano: No hay talleres.
* Trabajo en casa: Estudiar los siguientes temas de AprendeR1 y hacer los cuestionarios y problemas propuestos:
  + [Matrices](https://aprender-uib.github.io/AprendeR1/chap-matrix.html)
  + [Data frames](https://aprender-uib.github.io/AprendeR1/chap-df.html).    
 


### **Semana 1 del 17 del Febrero al 23 de Febrero** [Enlaces al material](https://ricuib.github.io/Enlaces/).

* Grupo grande: Hemos mostrado el acceso al material del curso. Instalación R, Rstudio y  otro software
*  Grupo medianos:  Taller de dos horas: Acabar instalación y ejercicios de [AprendeR1](https://aprender-uib.github.io/AprendeR1/) . 
* Trabajo en casa: Estudiar los siguientes temas de AprendeR1 y hacer los cuestionarios y problemas propuestos:
  + [Logística de R](https://aprender-uib.github.io/AprendeR1/chap-0.html)
  + [La calculadora](https://aprender-uib.github.io/AprendeR1/chap-calc.html)
  + [Un aperitivo: Introducción a la regresión lineal](https://aprender-uib.github.io/AprendeR1/chap-lm.html)
  + [Vectores y otros tipos de listas](https://aprender-uib.github.io/AprendeR1/chap-vect.html)

