---
title: "Planificación Semanal MAT3 2019-2020"
author: "Ricardo"
date: "26/2/2020"
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

**PLANIFICACIÓN SEMANAL** 
==========================================

**Semana 3 del 2 de marzo al 8 de marzo** [Enlaces al material](https://ricuib.github.io/Enlaces/).

* Grupo Grande: 
Acabaremos el  tema 
[Introducción variables aleatorias](https://joanby.github.io/bookdown-probabilidad/variables-aleatorias.html). 
Comenzaremos el tema de distribuciones notables que está dividido en dos partes:
  + [Distribuciones Notables Parte I: Distribuciones Discretas](https://joanby.github.io/probabilidad/Tema_3_1_Notables#1)
  + [Distribuciones Notables Parte II: Distribuciones Continuas. Cuantiles](https://joanby.github.io/probabilidad/Tema_3_2_Notables#1)

* Problemas propuestos
  + Introducción variables aleatorias: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%202%20-%20Variables%20Aleatorias.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-2---Variables-Aleatorias.pdf)
  + Distibuciones notables discretas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_discretas.Rmd), [pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_discretas.pdf)
  + Distribuciones notables continuas:[Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%203%20-%20Notables_continuas.Rmd)
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-3---Notables_continuas.pdf)

* Grupo mediano:  Dos horas de taller el jueves, traed los portátiles. Haremos problemas de combinatoria y probabilidad, también haremos ejercicios de los temas de R.
* Trabajo en casa: Estudiad los temas [7, 9 y 10](https://aprender-uib.github.io/AprendeR1/). Estudiar teoría y hacer problemas propuestos. !!! El tema 8 lo veremos en clase de grupo grande.




**Semana 2 del 24 de febrero al al  1 de marzo** [Enlaces al material](https://ricuib.github.io/Enlaces/).

* Grupo Grande: Probabilidad: [Prerrequisitos](https://joanby.github.io/bookdown-probabilidad/pre-requisitos-teor%C3%ADa-de-conjuntos-y-combinatoria.html), [Probabilidad](https://joanby.github.io/bookdown-probabilidad/probabilidad.html). [Introducción variables aleatorias](https://joanby.github.io/bookdown-probabilidad/variables-aleatorias.html). 
* Problemas propuestos
  + Prerrequisitos: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%200%20-%20Combinatoria.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-0---Combinatoria.pdf)
  + Probabilidad: [Rmd](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema%201%20-%20Probabilidad.Rmd), 
[pdf](https://github.com/joanby/probabilidad/blob/master/ejercicios/Tema-1---Probabilidad.pdf)
* Grupo mediano: No hay talleres.
* Trabajo en casa: Estudiar temas [5 y 6 AprendeR1](https://aprender-uib.github.io/AprendeR1/). Estudiar teoría y hacer problemas propuestos.

----------------------------------------------------------------------------------------



----------------------------------------------------------------------------------------

**Semana 1 del 17 del Febrero al 23 de Febrero** [Enlaces al material](https://ricuib.github.io/Enlaces/).

* Grupo grande: Hemos mostrado el acceso al material del curso. Instalación R, Rstudio y  otro software
*  Grupo medianos:  Taller de dos horas: Acabar instalación y ejercicios de [AprendeR1](https://aprender-uib.github.io/AprendeR1/) . 
* Trabajo en casa: Estudiar temas [1 a 4 AprendeR1](https://aprender-uib.github.io/AprendeR1/).


