---
title: "Matemàtiques III - Estadística. Grup 02. Curs 2019/2020"
author: "JL.Lisani"
date: "2/13/2020"
output: html_document
---

# Calendari:

* 18/02: Presentació. Material Aula Digital. Instal·lació R i Rstudio. Cursos online.  
  Feina a casa: llegir temes 1 a 4 AprendeR1.
* 20/02: Probabilitat: conjunts (apunts Pre-requisitos + 9-16 Probabilitat, codi R), combinatòria (apunts Pre-requisitos), probabilitat bàsica (3-27 apunts Probabilitat).
* 25/02: Probabilitat: prob. condicionada, independència, Bayes (28-68 apunts Probabilitat).  
  Feina a casa: llegir temes 5 i 6 AprendeR1.
* 27/02: (TALLER no avaluable) Exemple Estadística Descriptiva amb R (resum tallers 1, 2 i 3 JL curs 2018-2019). Edició amb Markdown.
* 03/03: Exercicis probabilitat i combinatòria. Exemple amb R (taller Ricardo configuració motors).  
  Feina a casa: llegir tema 7 AprendeR1.
* 05/03: (TALLER avaluable) Probabilitat i Combinatòria (inclou exemples amb R).
* 10/03: V.A. (1-57 apunts VA).  
  Feina a casa: llegir tema 8 AprendeR1.
* 12/03: V.A. (58-102 apunts VA).
* 17/03: Exercicis V.A.  
  Feina a casa: llegir tema 9 AprendeR1.
* 19/03: V.A. notables. Exercicis.
* 24/03: V.A. bidimensionals (apunts Varias_Variables).  
  Feina a casa: llegir tema 10 AprendeR1.
* 26/03: (TALLER avaluable) V.A. (inclou exemples amb R)
* 31/03: TCL. Mostreig. Estimació puntual.  
  Feina a casa: llegir temes 1, 2 i 3 AprendeR2.
* 02/04: CONTROL parcial: probabilitat i V.A. (pot incloure instruccions de R).  
* 07/04: Estimació puntual: acabar teoria i exercicis. Presentació de la pràctica per entregar.  
Mostrar exemples Aula Digital Ricardo 18/19 (part descriptiva):  
  * Activitats/Estimación y contrastes taller.
  * Activitats/EJEMPLO PROYECTO FINAL (PARTE 2).
  
--- SETMANA SANTA ---

* 21/04: Intervals de confiança.  
  Feina a casa: llegir tema 4 AprendeR2
* 23/04: Exercicis intervals de confiança.
* 28/04: Contrast d'hipòtesis (introducció).
* 30/04: (TALLER avaluable) Estimació puntual i intervals de confiança.
* 05/05: Contrast d'hipòtesis (1 mostra).  
  Feina a casa: llegir tema 5 AprendeR2.
* 07/05: Contrast d'hipòtesis (2 mostres).
* 12/05: Exercicis contrast d'hipòtesis.  
Pràctica ordinador, mostrar exemples Aula Digital Ricardo 18/19 (part inferencial): 
  * Activitats/Estimación y contrastes taller.
  * Activitats/EJEMPLO PROYECTO FINAL (PARTE 2).
* 14/05: (TALLER avaluable) Contrast d'hipòtesis.
* 19/05: Bondat d'ajustament.  
  Feina a casa: llegir tema 6 AprendeR2.
* 21/05: Tests d'independència.  
  Feina a casa: llegir tema 7 AprendeR2.
* 26/05: ANOVA 1 factor.  
  Feina a casa: llegir tema 9 AprendeR2.
* 28/05: (TALLER avaluable) Bondat d'ajustament i tests d'independència.
* 02/06: Regressió lineal simple. Clustering.  
  Feina a casa: llegir temes 10 i 11 AprendeR2.
* 04/06: (TALLER no avaluable) prova tipus examen.



