---
title: "Enunciado Proyecto MATIII 19-20 GINF"
author: Ricardo Alberich
output:
  html_document: 
    keep_md: yes
    number_sections: yes
    toc: yes
  pdf_document: 
    number_sections: yes
    toc: yes
    toc_depth: 4
urlcolor: blue
toccolor: red
header-includes:
  \renewcommand{\contentsname}{Contenidos}
---

#  Enunciado Proyecto final estadística.

**El proyecto final de estadística consiste en un trabajo en grupo. Se trata de encontrar un data set con el que hacer  un supuesto práctico de análisis estadístico.**

**El objetivo final es un informe editado de forma profesional que consistente en  un análisis de los datos y que presente algunas conclusiones, como se explica más adelante.**


## Indicaciones generales

* **El Proyecto Final se realiza en Grupos de a lo más 3 alumnos.** 
* **El Proyecto Final puntúa  2 puntos sobre 10 de la nota final.**


Los datos deben cumplir:

* **Con 100 o  muchas mas o observaciones mínimo.**
* **Con 8 variables mínimo con al menos dos categóricas y dos numéricas.**



### Ejemplos de conjuntos de datos 

* **Ejemplo de  conjunto de datos IDEAL para el proyecto**

[FIFA 19 complete player dataset 18k+ FIFA 19 players, ~90 attributes extracted from the latest FIFA database](https://www.kaggle.com/karangadiya/fifa19#data.csv)

* **Ejemplo de conjunto de datos interesante PERO NO PARA EL PROYECTO.**
[(LoL) League of Legends Ranked Games
Details from over 50,000 ranked games of LoL](https://www.kaggle.com/datasnaek/league-of-legends#champion_info.json)

## Sitios en los que buscar datos (data sets)

1. [Dataset Search - Google](https://toolbox.google.com/datasetsearch)
2. [Kaggle: Your Home for Data Science](https://www.kaggle.com/datasets)
3. [Datasets for Data Mining and Data Science - KDnuggets](https://www.kdnuggets.com/datasets/index.html)
4. [List of datasets for machine-learning research - Wikipedia](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)
5. [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/)

##  Fases del proyecto

Descripción de las tres fases del proyecto:

### Fase 1: Definición del proyecto (0.25 puntos de los 2 puntos totales):

1. Selección de los datos a analizar
2. Descripción de los datos
3. Objetivos iniciales el  proyecto.
4. Hay que dar un nombre al proyecto y al equipo.
5. El equipo debe nombrar un portavoz (el que habla en nombre del grupo con el profesor) y un secretario (que levanta acta de las reuniones del grupo  y de la participación de sus miembros)
6. El grupo debe redactar un contrato que firmarán todos sus miembros y entregarán copia al profesor. El contrato debe contener el compromiso de trabajo de cada miembro con el grupo. 
7. Hay que entregar al profesor un documento con todos los puntos anteriores. 

###  Fase 2: Análisis  exploratorio de los datos.  (0.75 puntos de los 2):

1. Estadísticos Descriptivos básicos globales
2. Estadísticos Descriptivos básicos por agrupaciones.
3. Análisis multidimensional: Relación entre las variables.
4. Presentación gráfica de los resultados  Anteriores.
5. Conclusiones: Interpretaciones básicas del análisis exploratorio.
6. Modificación, justificada, o confirmación de los objetivos del proyecto.
7. Hay que entregar un documento editado con R markdown (sin limitación de páginas)

### Fase 3: Entrega memoria final.  (1 puntos de los 2):
Redacción de la memoria final. Un documento bien editado:

1. Utilizando R markdown un documento en html y en pdf (el pdf  tiene que tener entre 4 y 8 páginas).
2. Con un índice y con los nombres de los autores del grupo de proyecto.
4. Un resumen con la parte del análisis exploratorio de los datos.
5. Un último apartado con alguna aplicación de estadística inferencia  a los datos 

